[toolchain]
# Stable
channel = "1.89.0" # rustc 1.89.0 (29483883e 2025-08-04)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]